#include <algorithm>
#include <cstdint>
#include <iostream>
#include <numeric>
#include <vector>

// The relationship between `k` and `p(n, k)` is formulated as follows.
//
// Let the `i`-th integer in the permutation `p(n, k)` be denoted by `p(n, k)[i]` (with 1-based indexing).
// When choosing which integer (from the inclusive range of `1` to `n`) to place in some index `i`, there are `n - i + 1` choices.
// Note that for the last index, `i = n`. There is only one choice, hence it is forced.
// This means that after some values for `p(n, k)[1]` to `p(n, k)[i]` have been chosen and fixed,
// there are `n - i` remaining positions, totalling `(n - i) * (n - i - 1) * ... * 1` choices matching the chosen prefix.
//
// The "first" permutation (i.e., the one with the lowest lexicographical rank) is the permutation `1 2 3 ... n`,
// and this is generated by choosing the lowest possible integer in the range `[1, n]` at each step moving from left to right
// that has not already been chosen by a position anywhere to the left.
// This means that permutations with a higher matching `k` value involve selecting an integer higher than the minimum available.
// For any index `i`, we are capable of making `n - i` such possible selections.
// Making such a selection further along the permutation (at higher indices) contributes *less* to the lexicographical rank,
// and for some index `i`, the number of ways we could make such selections in the suffix `p(n, k)[i+1..n]` is `(n-i)!`.
//
// To be more amenable to integer modulo operations, we can first decrement `k` to map it to the range `[0..(n! - 1)]`.
// Then, `k-1 = k_1 * (n-1)! + k_2 * (n-2)! + ... + k_{n-1} * 1! + k_n * 0!`, such that `0 <= k_i <= n-i`.
// Here, for every index `i`, `k_i` represents selecting the `k_i + 1`-th lowest possible integer for that index.
// That is, when `k_i = 0`, the lowest integer is selected.
// At its maximum value, `n! - 1 = (n-1) * (n-1)! + (n-2) * (n-2)! + ... + 1 * 1! + 0 * 0!`. This is provable by induction.

// From `k`, we get `p(n, k)`.
std::vector<uint64_t> get_p(uint64_t n, uint64_t k) {
    // This vector contains the resultant `p(n, k)`.
    std::vector<uint64_t> p(n);

    // This keeps track of the integers from `1` to `n`,
    // allowing us to keep track of the integers available
    // after already having chosen values for previous indices.
    std::vector<uint64_t> numbers(n);
    std::iota(numbers.begin(), numbers.end(), 1);

    // For every index `i`, we need to know `(n-i)!` to conduct the correct modulo.
    // We start with needing `(n-1)!` for index 1.
    uint64_t factorial = 1, factor = n-1;
    for (uint64_t i = 1; i <= n-1; ++i) {
        factorial *= i;
    }

    // We decrement `k` to map it to the range `[0..(n!-1)]`.
    --k;

    // We go from left to right, leaving out the final index since that one has a forced choice.
    for (std::size_t i = 0; i < n-1; ++i) {
        uint64_t k_i = k / factorial;
        // Since `numbers` contains the integers yet to be chosen in ascending order,
        // and `k_i` in our convention is zero-based, this position in the permutation is `numbers[k_i]`.
        p[i] = numbers[k_i];

        // Now that we have chosen this number, we must remove it from our `numbers` vector.
        numbers.erase(numbers.begin() + k_i);

        // Reduce `k` to no longer include its bigger factors contributing to previous indices,
        // and divide the factorial by the current factor to prepare for the next iteration.
        k = k % factorial;
        factorial /= factor;
        --factor;
    }

    // The last index must choose the only remaining integer.
    p[n-1] = numbers[0];

    return p;
}

// From `p(n, k)`, we get `k`.
uint64_t get_k(uint64_t n, std::vector<uint64_t>& p) {
    // This keeps track of the integers from `1` to `n`,
    // allowing us to keep track of the integers available
    // after already having chosen values for previous indices.
    std::vector<uint64_t> numbers(n);
    std::iota(numbers.begin(), numbers.end(), 1);

    // We keep track of the factorial `(n-i)!` needed for some index `i`.
    // We start with needing `(n-1)!` for index `1`.
    uint64_t factorial = 1, factor = n-1;
    for (uint64_t i = 1; i <= n-1; ++i) {
        factorial *= i;
    }

    // Our convention finds `k-1` which is in the range `[0..(n!-1)]`,
    // so we initialise with `1` to map it back to `[1..n!]`.
    uint64_t k = 1;

    for (std::size_t i = 0; i < n-1; ++i) {
        // We find the rank of the number at `p(n, k)[i]` for our given set of selectable integers.
        auto it = std::find(numbers.begin(), numbers.end(), p[i]);

        // When the lowest integer is selected, this distance is zero, consistent with our convention.
        k += std::distance(numbers.begin(), it) * factorial;

        // Now that we have chosen a certain number, we must remove it from our possible choices
        // for the indices after it. We also reduce the factorial we need to find `k_i` as per our expansion.
        numbers.erase(it);
        factorial /= factor;
        --factor;
    }

    return k;
}

int main() {
    // First, the number of test cases.
    int t;
    std::cin >> t;

    while (t--) {
        // For all types of sub-questions, both the type (1 or 2) and `n` are provided first.
        int type;
        uint64_t n;
        std::cin >> type >> n;

        if (type == 1) {
            // In Type 1 sub-questions, a single integer `k` is provided.
            uint64_t k;
            std::cin >> k;

            // We find `p(n, k)`, then output it with spaces in between.
            std::vector<uint64_t> p = get_p(n, k);
            for (std::size_t i = 0; i < p.size(); ++i) {
                if (i > 0) {
                    std::cout << ' ';
                }
                std::cout << p[i];
            }
            std::cout << '\n';

        } else if (type == 2) {

            // In Type 2 sub-questions, `n` integers representing the permutation `p(n, k)` are provided.
            std::vector<uint64_t> p(n);
            for (auto& element : p) {
                std::cin >> element;
            }

            // We find `k`, then output it.
            std::cout << get_k(n, p) << '\n';
        }
    }

    return 0;
}
